# Site settings
title: Le Duy Quang
email: work@leduyquang.com
description: > # this means to ignore newlines until "baseurl:"
  Thiet ke wordpress, xay dung cms cho doanh nghiep va quan ly adwords
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://leduyquang.com" # the base hostname & protocol for your site
twitter_username: quangbahoa
github_username:  quangbahoa

# Build settings
markdown: kramdown

# Build pre-setting
permalink: /blog/:title
relative_permalinks: false

paginate: 5
paginate_path: blog/page:num
